# Generated by Django 6.0.4 on 2026-04-13 10:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'merchant',
            },
        ),
        migrations.CreateModel(
            name='MerchantOrder',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('import_id', models.BigIntegerField()),
                ('order_date', models.DateTimeField()),
                ('bill_month', models.IntegerField(blank=True, null=True)),
                ('bill_date', models.DateTimeField(blank=True, null=True)),
                ('order_type', models.CharField(max_length=10)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('merchant_name', models.CharField(max_length=255)),
                ('merchant_id', models.BigIntegerField()),
                ('merchant_profit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('agent_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'merchant_order',
            },
        ),
        migrations.CreateModel(
            name='OrderImport',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=128)),
                ('succeed_rows', models.IntegerField(blank=True, null=True)),
                ('failed_rows', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, '未开始'), (2, '运行中'), (3, '成功'), (4, '失败')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'order_import',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('password_hash', models.CharField(max_length=512)),
                ('password_salt', models.CharField(max_length=64)),
                ('locked_out', models.DateTimeField(blank=True, null=True)),
                ('access_failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserAsset',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('frozen_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('available_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
            ],
            options={
                'db_table': 'user_asset',
            },
        ),
        migrations.CreateModel(
            name='ProfitAllocation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('settle_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('settle_date', models.DateTimeField(blank=True, null=True)),
                ('settle_source', models.CharField(choices=[('direct', 'direct'), ('subagent', 'subagent')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='profit_allocations', to='api.user')),
            ],
            options={
                'db_table': 'profit_allocation',
            },
        ),
        migrations.CreateModel(
            name='MerchantHistory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('merchant', models.ForeignKey(db_column='merchant_id', on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='api.merchant')),
                ('new_agent', models.ForeignKey(db_column='new_agent_id', on_delete=django.db.models.deletion.PROTECT, related_name='merchant_new_agent_histories', to='api.user')),
                ('old_agent', models.ForeignKey(blank=True, db_column='old_agent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_old_agent_histories', to='api.user')),
            ],
            options={
                'db_table': 'merchant_history',
            },
        ),
        migrations.AddField(
            model_name='merchant',
            name='agent',
            field=models.ForeignKey(blank=True, db_column='agent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
        migrations.CreateModel(
            name='AgentHistory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('new_superior', models.ForeignKey(blank=True, db_column='new_superior_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_agent_histories', to='api.user')),
                ('old_superior', models.ForeignKey(blank=True, db_column='old_superior_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_agent_histories', to='api.user')),
            ],
            options={
                'db_table': 'agent_history',
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.IntegerField(choices=[(1, '待提交'), (2, '待审批'), (3, '通过'), (4, '拒绝'), (5, '作废')])),
                ('audit_time', models.DateTimeField(blank=True, null=True)),
                ('audit_remark', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('audit_user', models.ForeignKey(blank=True, db_column='audit_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_withdraws', to='api.user')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='withdraws', to='api.user')),
            ],
            options={
                'db_table': 'withdraw',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subordinate', models.ForeignKey(db_column='subordinate_id', on_delete=django.db.models.deletion.PROTECT, related_name='agent_superiors', to='api.user')),
                ('superior', models.ForeignKey(db_column='superior_id', on_delete=django.db.models.deletion.PROTECT, related_name='agent_subordinates', to='api.user')),
            ],
            options={
                'db_table': 'agent',
                'constraints': [models.UniqueConstraint(fields=('superior', 'subordinate'), name='uq_agent_superior_subordinate')],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.user')),
            ],
            options={
                'db_table': 'user_role',
                'constraints': [models.UniqueConstraint(fields=('user', 'role'), name='uq_user_role_user_id_role')],
            },
        ),
    ]
