# Generated by Django 6.0.4 on 2026-04-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_merchant_merchantorder_orderimport_user_userasset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantorder',
            name='order_no',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
    ]
