# Generated by Django 6.0.4 on 2026-04-20 03:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


def backfill_invite_codes(apps, schema_editor):
    User = apps.get_model('api', 'User')
    InviteCode = apps.get_model('api', 'InviteCode')

    for user in User.objects.exclude(invite_code__isnull=True).exclude(invite_code=''):
        InviteCode.objects.get_or_create(
            code=str(user.invite_code).strip().lower(),
            defaults={
                'id': user.id,
                'user_id': user.id,
                'rate': Decimal('0.00'),
                'register_count': 0,
                'is_valid': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('register_count', models.IntegerField(default=0)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='api.user')),
            ],
            options={
                'db_table': 'invite_code',
            },
        ),
        migrations.RunPython(backfill_invite_codes, migrations.RunPython.noop),
    ]
