# Generated by Django 6.0.4 on 2026-04-22 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_walletrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitTaskRecord',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('run_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_ms', models.IntegerField(default=0)),
                ('data_scanned', models.IntegerField(default=0)),
                ('profit_data_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'profit_task_record',
            },
        ),
        migrations.RemoveConstraint(
            model_name='agent',
            name='uq_agent_superior_subordinate',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
