# Generated by Django 6.0.4 on 2026-04-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_profittaskrecord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profittaskrecord',
            old_name='duration_ms',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='profittaskrecord',
            name='bill_date',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterModelTable(
            name='profittaskrecord',
            table='profit_task',
        ),
    ]
