# Generated by Django 6.0.4 on 2026-04-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_merchantorder_to_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='import_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='merchant_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
