# Generated by Django 6.0.4 on 2026-04-24 07:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_order_bill_date_alter_order_import_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='profitallocation',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=18),
        ),
    ]
