# Generated by Django 6.0.4 on 2026-04-29 07:08

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_invitecode_rate_alter_profitallocation_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, '隐私政策'), (2, '用户协议')], verbose_name='协议类型')),
                ('name', models.CharField(max_length=100, verbose_name='协议名称')),
                ('platform', models.IntegerField(blank=True, choices=[(1, '全部'), (2, 'Web'), (3, '小程序'), (4, 'App'), (5, '其他')], null=True, verbose_name='平台')),
                ('status', models.IntegerField(choices=[(1, '待发布'), (2, '已发布')], default=1, verbose_name='状态')),
                ('content', models.TextField(verbose_name='协议内容')),
                ('file_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='文件名')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '协议管理',
                'verbose_name_plural': '协议管理',
                'db_table': 'term',
            },
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))]),
        ),
        migrations.AlterField(
            model_name='profitallocation',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))]),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))]),
        ),
    ]
