# Generated by Django 6.0.4 on 2026-04-29 10:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_term_alter_invitecode_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=50, unique=True, verbose_name='存储文件名')),
                ('origin_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('file_ext', models.CharField(max_length=10, verbose_name='文件扩展名')),
                ('signature_key', models.CharField(max_length=64, verbose_name='签名密钥')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('upload_by', models.ForeignKey(blank=True, db_column='upload_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='api.user', verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '附件管理',
                'verbose_name_plural': '附件管理',
                'db_table': 'attachment',
            },
        ),
    ]
