# Generated by Django 6.0.4 on 2026-04-29 11:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('card_no', models.CharField(max_length=32, unique=True, verbose_name='银行卡号')),
                ('name', models.CharField(max_length=50, verbose_name='持卡人姓名')),
                ('id_no', models.CharField(max_length=18, verbose_name='身份证号')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='预留手机号')),
                ('card_photo', models.CharField(max_length=50, verbose_name='银行卡照片')),
                ('id_photo_badge', models.CharField(max_length=50, verbose_name='身份证国徽照片')),
                ('id_photo_face', models.CharField(max_length=50, verbose_name='身份证人像照片')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='bank_cards', to='api.user')),
            ],
            options={
                'verbose_name': '银行卡管理',
                'verbose_name_plural': '银行卡管理',
                'db_table': 'bank_card',
            },
        ),
    ]
