# Generated by Django 6.0.4 on 2026-04-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_bankcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='bank_card_holder',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='持卡人姓名'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='bank_card_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='银行卡ID'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='bank_card_no',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='银行卡号'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', '银行卡'), ('qr', '收款码')], max_length=10, null=True, verbose_name='收款方式'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='receiving_qr_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='收款码照片'),
        ),
    ]
