# Generated by Django 6.0.4 on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_withdraw_bank_card_holder_withdraw_bank_card_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agent_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
