# Generated by Django 6.0.4 on 2026-05-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_order_agent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='card_photo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='银行卡照片'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='id_photo_badge',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='身份证国徽照片'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='id_photo_face',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='身份证人像照片'),
        ),
    ]
