# Generated by Django 6.0.4 on 2026-05-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_bankcard_card_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletrecord',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AddField(
            model_name='walletrecord',
            name='outer_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='外部ID'),
        ),
        migrations.AddField(
            model_name='walletrecord',
            name='outer_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='外部数据类型'),
        ),
    ]
