# Generated by Django 6.0.4 on 2026-05-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_wallet_record_outer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=22, null=True, unique=True),
        ),
    ]
