# Generated by Django 6.0.4 on 2026-05-12 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCodeSeq',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'invite_code_seq',
            },
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
